### PR TITLE
Update Stacks from 1.41 to 1.44

### PR DESCRIPTION
**Pull request by pseudogene**
Update Stacks from 1.41 to 1.44 (ready for leave development branch)

### CODE REVIEW

**Comment by ypriverol** [comment]
@prvst can we change in sandbox all the namespace from biodocker to biocontainers. Can you accepted this PR.

**Comment by prvst** [comment]
have you noticed the biodocker base image there ?

**Comment by ypriverol** [comment]
@prvst I guess all the users needs to know that:

```
 Tags:             Genomics
 -# Provides:         Stacks 1.41		 +# Provides:         Stacks 1.44
  # Base Image:       biodckr/biodocker:latest		  # Base Image:       biodckr/biodocker:latest
 -# Build Cmd:        docker build --rm -t biodckr/stacks 1.41/.		 +# Build Cmd:        docker build --rm -t biodckr/stacks 1.44/.
  # Pull Cmd:         docker pull biodckr/stacks		  # Pull Cmd:         docker pull biodckr/stacks
  # Run Cmd:          docker run --rm biodckr/stacks <tool> <options>		  # Run Cmd:          docker run --rm biodckr/stacks <tool> <options>
  #################################################################		  #################################################################
 @@ -18,7 +18,7 @@
  FROM biodckr/biodocker:latest		  FROM biodckr/biodocker:latest
  		  
  ################## BEGIN INSTALLATION ###########################		  ################## BEGIN INSTALLATION ###########################
 -ENV STACKVERSION 1.41		 +ENV STACKVERSION 1.44
  		  
  USER root		  USER root
```

this has change.

**Comment by pseudogene** [comment]
I used the old dockerfile format. Sorry about that. I checked and updated both the base image and the overall dockerfile layout, including the metadata bit.

**Pull request closed without merging**
