### PR TITLE
Adding STAR new container

### PR DESCRIPTION
**Pull request by r78v10a07**
Hi,
I've added a new container for STAR.
Cheers,
Roberto

### CODE REVIEW

**Comment by bgruening** [comment]
Hi @r78v10a07!

Please note that we already have a biocontainer for Star here: https://quay.io/repository/biocontainers/star?tab=tags

**Comment by r78v10a07** [comment]
Hi,

Sorry, I was working with the git repo and I didn’t find the STAR there.

Thanks,
Roberto



--

Roberto Vera Alvarez, PhD


Profiles:

LinkedIn <http://www.linkedin.com/in/robertoveraalvarez>, ResearchGate
<http://www.researchgate.net/profile/Roberto_Vera_Alvarez>, Google Citations
<http://scholar.google.it/citations?user=X9OKjuEAAAAJ>, Twitter
<http://twitter.com/r78v10a07>

Skype user: r78v10a07

**Comment by ypriverol** [comment]
you need to specify the latest version that the registry give you.

**Comment by r78v10a07** [comment]
OK, thanks.
This is working now:

docker pull quay.io/biocontainers/star:2.5.3a--0

Question:
Why do you have containers in quay.io that are not in the github repo?

Best,
Roberto



--

Roberto Vera Alvarez, PhD


Profiles:

LinkedIn <http://www.linkedin.com/in/robertoveraalvarez>, ResearchGate
<http://www.researchgate.net/profile/Roberto_Vera_Alvarez>, Google Citations
<http://scholar.google.it/citations?user=X9OKjuEAAAAJ>, Twitter
<http://twitter.com/r78v10a07>

Skype user: r78v10a07

**Comment by ypriverol** [comment]
This containers are automatically generated from bioconda packages.

**Comment by bgruening** [comment]
Quay.io has a better API (last time I checked) and we auto-generate these repos.

**Comment by r78v10a07** [comment]
OK, thanks.
I will start using quay.io instead of the github repo from now on.
Cheers!!



--

Roberto Vera Alvarez, PhD


Profiles:

LinkedIn <http://www.linkedin.com/in/robertoveraalvarez>, ResearchGate
<http://www.researchgate.net/profile/Roberto_Vera_Alvarez>, Google Citations
<http://scholar.google.it/citations?user=X9OKjuEAAAAJ>, Twitter
<http://twitter.com/r78v10a07>

Skype user: r78v10a07

**Comment by ypriverol** [comment]
the registry gives you also the containers, the one in quey.io and dockerstore bioconteiners.pro/registry

**Comment by r78v10a07** [comment]
Guys,

I’m creating a container for a C++ software that I wrote and it is used in
a RNA-Seq pipeline.

I’m having problems while compiling the software due to libz

How can I start the ubuntu image you’re using as base for the biocontainers?

Thanks,
Roberto



--

Roberto Vera Alvarez, PhD


Profiles:

LinkedIn <http://www.linkedin.com/in/robertoveraalvarez>, ResearchGate
<http://www.researchgate.net/profile/Roberto_Vera_Alvarez>, Google Citations
<http://scholar.google.it/citations?user=X9OKjuEAAAAJ>, Twitter
<http://twitter.com/r78v10a07>

Skype user: r78v10a07

**Comment by r78v10a07** [comment]
I’m trying this:

hydrus:0.0.1> docker ps -a
CONTAINER ID        IMAGE                         COMMAND
CREATED             STATUS                     PORTS               NAMES
b39528d69db1        biocontainers/biocontainers   "/bin/bash"         10
minutes ago      Exited (0) 9 seconds ago
tender_lalande
hydrus:0.0.1> docker start b39528d69db1
b39528d69db1
hydrus:0.0.1> docker attach b39528d69db1
You cannot attach to a stopped container, start it first
hydrus:0.0.1>



--

Roberto Vera Alvarez, PhD


Profiles:

LinkedIn <http://www.linkedin.com/in/robertoveraalvarez>, ResearchGate
<http://www.researchgate.net/profile/Roberto_Vera_Alvarez>, Google Citations
<http://scholar.google.it/citations?user=X9OKjuEAAAAJ>, Twitter
<http://twitter.com/r78v10a07>

Skype user: r78v10a07

**Pull request closed without merging**
